apiVersion: v1
kind: Secret
metadata:
  name: streaming-data-secrets
type: Opaque
stringData:
  KAFKA_HOST: "<KAFKA_HOST>"
  KAFKA_USERNAME: "<KAFKA_USERNAME>"
  KAFKA_PASSWORD: "<KAFKA_PASSWORD>"
  PG_WAREHOUSE_HOST: "<POSTGRES_HOST>"
  PG_WAREHOUSE_DBNAME: "<POSTGRES_DATABASE>"
  PG_WAREHOUSE_USER: "<POSTGRES_USER>"
  PG_WAREHOUSE_PASSWORD: "<POSTGRES_PASSWORD>"
  REDIS_HOST: "<REDIS_HOST>"
  REDIS_PASSWORD: "<REDIS_PASSWORD>"
